#deployment manifest for nodejstest1
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.App.name }}
  labels:
    app: {{ .Values.App.app }}
  namespace: {{ .Values.App.namespace }}
spec:
  replicas: {{ .Values.App.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.App.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.App.app }}
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: Type
      #           operator: NotIn
      #           values:
      #           - stateful
      pullPolicy: {{ .Values.App.pullPolicy }}
      containers:
        - name: {{ .Values.App.name }}
          image: "{{ .Values.App.image.repository }}:{{ .Values.App.image.tag }}"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP 
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
  revisionHistoryLimit: 3
  strategy:
    canary: # A new field that used to provide configurable options for a Canary strategy
      maxSurge: "10%"
      maxUnavailable: 1
      steps:
      - setWeight: {{ .Values.canary.setWeight }}
      - pause:
          duration: 60
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
  namespace: {{ .Values.Service.namespace }}
  labels:
    app: {{ .Values.Service.app }}
spec:
#    type: {{ .Values.Service.type }}
  ports:
    - port: {{ .Values.Service.port }}
#       targetPort: http
      protocol: TCP
#       name: http
  selector:
    app: {{ .Values.Service.app }}
