#deployment manifest for nodejstest1
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.App.name }}
  labels:
    app: {{ .Values.App.app }}
  namespace: {{ .Values.App.namespace }}
spec:
  replicas: {{ .Values.App.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.App.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.App.app }}
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: Type
      #           operator: NotIn
      #           values:
      #           - stateful
      pullPolicy: {{ .Values.App.pullPolicy }}
      containers:
        - name: {{ .Values.App.name }}
          image: "{{ .Values.App.image.repository }}:{{ .Values.App.image.tag }}"
        
        # env:
        #   - name: student
        #     valueFrom:
        #       secretKeyRef:
        #         name: student-secret
        #         key: student
          ports:
            - name: http
            - containerPort: 8080
              protocol: TCP 
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      revisionHistoryLimit: 3
      strategy:
        canary: #Indicates that the rollout should use the Canary strategy
          maxSurge: "25%"
          maxUnavailable: 0
          steps:
          - setWeight: 10
          - pause:
              duration: "30s" # 1 hour
          - setWeight: 50
          - pause: {} # pause indefinitely

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
  namespace: {{ .Values.Service.namespace }}
  labels:
    app: {{ .Values.Service.app }}
spec:
  type: {{ .Values.Service.type }}
  ports:
    - port: {{ .Values.Service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.Service.app }}
